baseURL = "http://www.inspires.cn"
languageCode = "zh-cn"
title = "Blog For Blockchain"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
uglyurls = true

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/post"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/bingge1"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Links"
  weight = 40
  identifier = "links"
  url = "/links.html"


[[menu.main]]
  name = "About"
  weight = 50
  identifier = "about"
  url = "/about.html"


# Add your own params here
[params]
  author = "Jon Chiang"
  avatar = "/img/avatar.jpg"
  seotitle = "冰歌的区块链博客"
  subtitle = "~ Follow Your Heart ~"
  description = "Change The World With The Line Code"
  paginate = 10

  # Choose your social networks
  email = "jonchiang@sina.com"
  github = "bingge1"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  weibo = "sandyJan"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
 
[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

 
ICP = "粤ICP备14049281号-1"
