baseURL = "http://www.inspires.cn"
languageCode = "zh-cn"
title = "Blog For Blockchain"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true


# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/bingge1"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Ritchie Zhu"
  avatar = "/img/avatar.jpg"
  seotitle = "Hugo Blog (SEO Version)"
  subtitle = "~ Keep It Simple & Stupid ~"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "name@domain.com"
  github = "bingge1"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  weibo = "weibo_username"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
 

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
